Fixing build error on MSVC compiler.
Root Cause:
Function countOnes was using uint32_t instead of uint64_t for the 64 bit integer. This caused the following build error on MSVC:
error C2084: function 'uint32_t countOnes(uint32_t)' already has a body

Corrective Action:
Changed the param type to uint64_t